dbt_project:
nyc_parking_violations:
  outputs:
    dev:
      type: duckdb
      path: "C:\\Users\\bhara\\Documents\\Data Engineer\\DBT\\data\\nyc_parking_violations.db"
      threads: 1

    prod:
      type: duckdb
      path: "C:\\Users\\bhara\\Documents\\Data Engineer\\DBT\\data\\prod_nyc_parking_violations.db"
      threads: 4

  target: dev
